name: Deploy (DEV)

env:
  STAGE: DEV
  BUCKET_NAME: smmp-web-client-dev
  PROJECT_NAME: web-client
  CLOUDFRONT_ID: ERLJJ28QGEOP

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build
      run: npm run build:dev

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/$PROJECT_NAME s3://$BUCKET_NAME

    - name: Clean Cloudfront cache
      if: success()
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
